# fish completion for awapp
complete -c awapp -l apikey          -d 'OpenWeatherMap API key'
complete -c awapp -l city            -d 'City to fetch, e.g. Fortaleza,BR'
complete -c awapp -l use-ip          -d 'Use IP-location weather'
complete -c awapp -l no-ip-prompt    -d 'Skip the IP-location prompt'
complete -c awapp -l interval        -d 'Poll interval'
complete -c awapp -l fps             -d 'Animation frame rate'
complete -c awapp -s f               -d 'Start with Fahrenheit'
complete -c awapp -l color           -d 'Enable 256-color output'
complete -c awapp -l stars           -d 'Star field: light, full, off'
complete -c awapp -l light-key       -d 'Light-pollution API key'
complete -c awapp -l moon            -d 'Moon visibility: auto, on, off'
complete -c awapp -l phase           -d 'Override moon phase'
complete -c awapp -l eclipse         -d 'Simulated lunar eclipse'
complete -c awapp -l eclipse-duration -d 'Lunar eclipse length'
complete -c awapp -l solar-eclipse   -d 'Simulated solar eclipse'
complete -c awapp -l solar-eclipse-duration -d 'Solar eclipse length'
complete -c awapp -l size            -d 'Sun/Moon diameter %'
complete -c awapp -l season          -d 'Leaf season'
complete -c awapp -l leaves          -d 'Enable the leaf/snow layer'
complete -c awapp -l save-config     -d 'Save toggles to config on quit'
complete -c awapp -l list-config     -d 'Print resolved config and exit'
complete -c awapp -l config          -d 'Path to config.json'
complete -c awapp -l version         -d 'Print version and exit'
